### PR TITLE
convenience methods to append time series to existing series

### PR DESCRIPTION
**Pull request by mbannert**
When scraping or mining data you often receive single values that should be added to an existing time series. In R, simply using concat strips all sorts of class from objects. I.e. an object of class ts is not
a ts anymore after c(my_ts,20) after adding an observation.

I added a set of methods to ease the pain. Tested for time series in data.frame, xts, ts, zoo and data.table objects. Could also see an prepend function to the same for at the beginning of the series. This is much less used and a little harder to implement thoroughly, so I left it out. But we could keep this in mind in case you like it.

Check the examples to see if you like it. HTH !

### CODE REVIEW

**Comment by mbannert** [comment]
One reason why this is cool, even though there's already `ts_c` is that the appended vector does not have to be a `ts` object in the first place. Turning single observations into `ts` objects can be tricky because it's hard to guess the frequency from only one observation.

**Comment by christophsax** [comment]
Thanks! I guess this is useful.

I think we could also do this in `ts_rbind`, similar to this, which is currently working:

```
ts_rbind(window(mdeaths, end = 1978), fdeaths)
```

So we could do something like:
```
ts_rbind(window(mdeaths, end = 1978), 1:10)
```

Perhaps this should also work:

```
ts_rbind(window(mdeaths, end = 1978), 1:2, fdeaths)
```

If we have a numeric vector, it should simply inherit the time series properties from the previous time series, starting one period after the previous ends.

And finally, how about:
```
ts_rbind(12, window(mdeaths, end = 1978), 1:2, fdeaths)
```
Should this work as well?

**Comment by mbannert** [comment]
Hmm I get errors when I run your suggestions... E.g. 

```
ts_rbind(window(mdeaths, end = 1978), 1:10)
```

leads to: 
```
 Error in vapply(ll, relevant_class, "") : values must be length 1,
 but FUN(X[[2]]) result is length 0
```
might have to do with my fork but something goes wrong here....

**Comment by christophsax** [comment]
No, sorry. This is not yet implemented. Was just brainstorming about the syntax...

**Comment by christophsax** [comment]
months later....

`ts_rbind` has been renames to `ts_bind`, and will prolong time series with numeric input. That should do it, @mbannert?

``` r
library(tsbox)
stopifnot(packageVersion("tsbox") >= "0.0.10.0")

ts_bind(ts_window(mdeaths, end = "1975-12-01"), fdeaths)
#>       Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
#> 1974 2134 1863 1877 1877 1492 1249 1280 1131 1209 1492 1621 1846
#> 1975 2103 2137 2153 1833 1403 1288 1186 1133 1053 1347 1545 2066
#> 1976  767 1141  896  532  447  420  376  330  357  445  546  764
#> 1977  862  660  663  643  502  392  411  348  387  385  411  638
#> 1978  796  853  737  546  530  446  431  362  387  430  425  679
#> 1979  821  785  727  612  478  429  405  379  393  411  487  574
ts_bind(mdeaths, c(2, 2))
#>       Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
#> 1974 2134 1863 1877 1877 1492 1249 1280 1131 1209 1492 1621 1846
#> 1975 2103 2137 2153 1833 1403 1288 1186 1133 1053 1347 1545 2066
#> 1976 2020 2750 2283 1479 1189 1160 1113  970  999 1208 1467 2059
#> 1977 2240 1634 1722 1801 1246 1162 1087 1013  959 1179 1229 1655
#> 1978 2019 2284 1942 1423 1340 1187 1098 1004  970 1140 1110 1812
#> 1979 2263 1820 1846 1531 1215 1075 1056  975  940 1081 1294 1341
#> 1980    2    2
ts_bind(mdeaths, 3, ts_bind(fdeaths, c(99, 2)))
#>       Jan  Feb  Mar  Apr  May  Jun  Jul  Aug  Sep  Oct  Nov  Dec
#> 1974 2134 1863 1877 1877 1492 1249 1280 1131 1209 1492 1621 1846
#> 1975 2103 2137 2153 1833 1403 1288 1186 1133 1053 1347 1545 2066
#> 1976 2020 2750 2283 1479 1189 1160 1113  970  999 1208 1467 2059
#> 1977 2240 1634 1722 1801 1246 1162 1087 1013  959 1179 1229 1655
#> 1978 2019 2284 1942 1423 1340 1187 1098 1004  970 1140 1110 1812
#> 1979 2263 1820 1846 1531 1215 1075 1056  975  940 1081 1294 1341
#> 1980    3    2
```

**Comment by mbannert** [comment]
Hopefully this doesn't reopen the issue. But yes, this does the job. Great!

**Pull request closed without merging**
